### ISSUE TITLE
API fields are readonly

### ISSUE THREAD

**Issue by nitech** [quantity-digital/commerce-shipmondo#1]
API fields are readonly when entering settings 

![image](https://github.com/quantity-digital/commerce-shipmondo/assets/1279436/bc153f90-6075-4ab3-9270-eb3174073f1a)

Running newest Craft Commerce and newest Shipmondo.

**Comment by bjerringgaard** [comment]
I will have a fix for this in the next release

**Comment by nitech** [comment]
Thanks. Do you intend to reach a wider audience with the plugin, or is it more to serve your own customers?

**Comment by bjerringgaard** [comment]
The plugin has initially just been put on the store, because there where no other option, and a user of our craft3 plugin requested it.

The intend is to update the plugin as the features gets requested by our own customers, in order to earn some money on the development.

But errors like these, as well as the docs, for an easier setup, is something i will get updated as soon as i have some left over time :D

**Comment by nitech** [comment]
Ah. I totally get where you are standing. Sounds like there should be an option to publish plugins only for a set number of customers. Happy coding anyhow ;-)

**Comment by bjerringgaard** [comment]
Fixed in Release 4.0.7
